name = "backend"
compatibility_date = "2023-12-01"

#these env. variable should be avoided pushing to the github, after deploying to cloudflare workers, these varaiable fits in there.. so you don't need to commit these.
[vars]
DATABASE_URL=""
JWT_SECRET=""

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
